version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "lib/package.json" }}
            - v1-dependencies-

      - run:
          name: npm install
          command: npm install
          working_directory: lib

      - save_cache:
          paths:
            - lib/node_modules
          key: v1-dependencies-{{ checksum "lib/package.json" }}

      - run:
          name: npm test
          command: npm test
          working_directory: lib
